// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sorfian/go-todo-list/app"
	"github.com/sorfian/go-todo-list/controller"
	"github.com/sorfian/go-todo-list/repository"
	"github.com/sorfian/go-todo-list/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeTestApp initializes the test application with all dependencies
func InitializeTestApp() *TestDependencies {
	userRepository := repository.NewUserRepository()
	db := app.ProvideDatabase()
	validate := app.ProvideValidator()
	userService := service.NewUserService(userRepository, db, validate)
	userController := controller.NewUserController(userService)
	contactRepository := repository.NewContactRepository()
	contactService := service.NewContactService(contactRepository, db, validate)
	contactController := controller.NewContactController(contactService)
	addressRepository := repository.NewAddressRepository()
	addressService := service.NewAddressService(addressRepository, contactRepository, db, validate)
	addressController := controller.NewAddressController(addressService)
	testDependencies := ProvideTestDependencies(userController, contactController, addressController, userRepository, db)
	return testDependencies
}

// wire.go:

// TestDependencies holds all test dependencies
type TestDependencies struct {
	App            *fiber.App
	DB             *gorm.DB
	UserRepository repository.UserRepository
}

// ProvideTestDependencies creates and configures all test dependencies
func ProvideTestDependencies(
	userController controller.UserController,
	contactController controller.ContactController,
	addressController controller.AddressController,
	userRepository repository.UserRepository,
	db *gorm.DB,
) *TestDependencies {
	app2 := setupTestFiberApp(userController, contactController, addressController, userRepository, db)
	return &TestDependencies{
		App:            app2,
		DB:             db,
		UserRepository: userRepository,
	}
}
