// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/sorfian/go-contact-management-api/app"
	"github.com/sorfian/go-contact-management-api/controller"
	"github.com/sorfian/go-contact-management-api/repository"
	"github.com/sorfian/go-contact-management-api/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies
func InitializeApp() *fiber.App {
	userRepository := repository.NewUserRepository()
	db := app.ProvideDatabase()
	validate := app.ProvideValidator()
	userService := service.NewUserService(userRepository, db, validate)
	userController := controller.NewUserController(userService)
	contactRepository := repository.NewContactRepository()
	contactService := service.NewContactService(contactRepository, db, validate)
	contactController := controller.NewContactController(contactService)
	addressRepository := repository.NewAddressRepository()
	addressService := service.NewAddressService(addressRepository, contactRepository, db, validate)
	addressController := controller.NewAddressController(addressService)
	fiberApp := ProvideFiberApp(userController, contactController, addressController, userRepository, db)
	return fiberApp
}

// wire.go:

// ProvideFiberApp creates and configures the Fiber app
func ProvideFiberApp(
	userController controller.UserController,
	contactController controller.ContactController,
	addressController controller.AddressController,
	userRepository repository.UserRepository,
	db *gorm.DB,
) *fiber.App {
	return setupFiberApp(userController, contactController, addressController, userRepository, db)
}
